package:
  name: testify
  version: !!str 0.5.6

source:
  fn: testify-0.5.6.tar.gz
  url: https://pypi.python.org/packages/source/t/testify/testify-0.5.6.tar.gz
  md5: 8b705408dd30fb0228eaf1dffcce8c8e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - testify = testify:main
    #
    # Would create an entry point called testify that calls testify.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - mock
    - pyyaml
    - sqlalchemy
    - tornado <2.0.0

  run:
    - python
    - mock
    - pyyaml
    - sqlalchemy
    - tornado <2.0.0

test:
  # Python imports
  imports:
    - testify
    - testify.contrib
    - testify.plugins
    - testify.utils

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/Yelp/Testify
  license: Apache Software License
  summary: 'Testing framework'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
