package:
  name: tornado
  version: !!str 1.2.1

source:
  git_url: https://github.com/tornadoweb/tornado.git
  git_tag: v1.2.1

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tornado = tornado:main
    #
    # Would create an entry point called tornado that calls tornado.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - certifi
    - backports.ssl_match_hostname

  run:
    - python
    - certifi
    - backports.ssl_match_hostname

test:
  # Python imports
  imports:
    - tornado

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.tornadoweb.org/
  license: Apache Software License
  summary: 'Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
