package:
  name: webob
  version: !!str 1.4

source:
  fn: WebOb-1.4.tar.gz
  url: https://pypi.python.org/packages/source/W/WebOb/WebOb-1.4.tar.gz
  md5: 8437607c0cc00c35f658f972516ffb55
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - webob = webob:main
    #
    # Would create an entry point called webob that calls webob.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - webob

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://webob.org/
  license: MIT License
  summary: 'WSGI request and response object'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
